name: Code Quality

on:
  push:
    branches: [ master ]
  pull_request: ~

env:
  PHP_VERSION: 8.0
  APPLICATION_NAME: cache
  GCP_REGION: us-east4
  PR_NUMBER: ${{ github.event.number }}
  NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
  NEW_RELIC_APP_NAME: ${{ secrets.NEW_RELIC_APP_NAME }}

jobs:
  test-php-80:
    name: Code quality PHP 8.0
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: xdebug

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Lint
        run: composer lint:check

      - name: PHP Static Analysis
        run: composer phpstan

      - name: Unit Test
        run: composer phpunit